### PR TITLE
Add landing page

### PR DESCRIPTION
**Pull request by rasfa98**
landing-page

### CODE REVIEW

**Comment by kshitij10496** [comment]
Hey @rasfa98 
This looks great! Almost as minimal as it can get.

Just a couple of suggestions:
- [ ] A link to the API's base URL at the top: https://hercules-10496.herokuapp.com/api/v1
- [ ] Hyperlink all the endpoints to their respective URI (as being currently done in the README)
- [ ] Tabular formatting of the endpoint and their functionality in order to add some visual assistance for the reader.

**Comment by rasfa98** [comment]
@kshitij10496 Thanks! I will fix it according to your suggestions! 😄

**Comment by rasfa98** [comment]
landing-page-2

**Comment by rasfa98** [comment]
I have never written something in GO but I will give it a shot! 😄

**Comment by thealphadollar** [comment]
I guess that's even better then :smile:

**Comment by rasfa98** [comment]
@thealphadollar It may be a better idea for someone with a bit more experience with GO to fix this since I do not have time to setup the environment right now 😄 You could merge this PR and then open a new issue 😃

**Comment by kshitij10496** [comment]
@rasfa98 @thealphadollar I will open a new issue for adding a handler in order to render the static page. 😃 
Merging this in!

**Pull request merged**
